
version: 1

formatters:
  standard:
    format: '[%(asctime)s] %(name)s %(levelname)7s [%(process)5d] | %(message)s'
    datefmt: '%m.%d | %H:%M:%S'
  plain:
    format: '%(name)s - %(message)s'

handlers:
  logfile:
    class: logging.FileHandler
    filename: irt2.log
    formatter: standard
  stdout:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

loggers:
  root:
    level: INFO
    handlers:
      - logfile

